import type { Metadata } from "next";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLinkedin, faSquareGithub } from "@fortawesome/free-brands-svg-icons";
import NavBar from "./components/navbar/Navbar";
import "./styles/globals.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <section className="flex justify-center body-section-height">
          {children}
          <aside className="w-14 absolute h-full right-0 content-center">
            <a
              href="https://www.linkedin.com/in/mauricio-lopez-ruiz-0851a2106/"
              className="links"
            >
              <FontAwesomeIcon icon={faLinkedin} beat />
            </a>
            <a
              href="https://github.com/Misho506"
              className="links"
            >
              <FontAwesomeIcon icon={faSquareGithub} beat />
            </a>
          </aside>
        </section>
        <footer className="flex items-center justify-center">
          <a
            className="links"
            href={`mailto:maurisho01@gmail.com?subject=${encodeURIComponent("Hi Mauricio") || ''}&body=${encodeURIComponent("I want to contant ") || ''}`}
          >
            <label className="custom-link">Mail me!</label>
          </a>
        </footer>
      </body>
    </html>
  );
}
